import Head from 'next/head';
import { LayoutProps } from '../../types/types';

const Layout = ({ headerOption, children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{headerOption.title} | next-auth-google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex justify-center align-center items-center">
        {children}
      </div>
    </>
  );
};

export default Layout;
